### PR TITLE
PHPLIB-581, PHPLIB-585: Check error labels for retryable writes spec tests 

### PR DESCRIPTION
**Pull request by jmikola**
https://jira.mongodb.org/browse/PHPLIB-581
https://jira.mongodb.org/browse/PHPLIB-585

### CODE REVIEW

**Comment by alcaeus** [comment]
Code changes LGTM, but it looks like there are issues on sharded clusters:
```
[2020/09/14 22:52:25.943] 1) MongoDB\Tests\SpecTests\RetryableWritesSpecTest::testRetryableWrites with data set "insertOne-serverErrors: InsertOne fails after multiple retryable writeConcernErrors" (stdClass Object (...), array(stdClass Object (...), stdClass Object (...)), array(stdClass Object (...), stdClass Object (...)))
[2020/09/14 22:52:25.955] Exception should have error label: RetryableWriteError
[2020/09/14 22:52:25.955] Failed asserting that false is true.
[2020/09/14 22:52:25.955] /data/mci/b82e98f545702d703f1560df2dd3e718/src/tests/SpecTests/ErrorExpectation.php:185
[2020/09/14 22:52:25.955] /data/mci/b82e98f545702d703f1560df2dd3e718/src/tests/SpecTests/Operation.php:273
[2020/09/14 22:52:25.955] /data/mci/b82e98f545702d703f1560df2dd3e718/src/tests/SpecTests/RetryableWritesSpecTest.php:47
```

**Comment by jmikola** [comment]
> but it looks like there are issues on sharded clusters:

Interesting. My understanding is that the sharded cluster issue is exactly what [DRIVERS-1356](https://jira.mongodb.org/browse/DRIVERS-1356) was attempting to fix. I'll look into this some more.

**Comment by jmikola** [comment]
Depends on https://github.com/mongodb/mongo-php-driver/pull/1162 for [PHPC-1683](https://jira.mongodb.org/browse/PHPC-1683).

**Comment by alcaeus** [comment]
@jmikola I've reconfigured the evergreen patch build to test against the current stable driver release as well as the upcoming 1.8 release. This should tell us whether the bug is actually fixed.

**Comment by jmikola** [comment]
> I've reconfigured the evergreen patch build to test against the current stable driver release as well as the upcoming 1.8 release. This should tell us whether the bug is actually fixed.

I didn't see any updated Evergreen patch build after that comment. I just pushed again and the current patch build is using "latest stable driver", which i assume is https://github.com/mongodb/mongo-php-library/blob/master/.evergreen/config.yml#L445. Can you clue me in on how you manually changed the build to use "latest-minor-dev" (preferable to "latest-dev")?

**Review by alcaeus — APPROVED** [review]
Patch build succeeds on the upcoming driver release, so good to merge this one 👍

**Comment by jmikola** [comment]
> Patch build succeeds on the upcoming driver release, so good to merge this one after a driver patch release

I now see the "latest-minor-dev" builds in https://spruce.mongodb.com/version/5f635e415623432d5b76c1ad/tasks. Thank you!

**Comment by jmikola** [comment]
Note: this just needs the PHPC dependency bumped to 1.8.1.

**Pull request merged**
