### PR TITLE
PHPLIB-162: Support database and collection selection via __get()

### PR DESCRIPTION
**Pull request by jmikola**
https://jira.mongodb.org/browse/PHPLIB-162

### CODE REVIEW

**Comment by kamillo1888** [comment]
+1

**Comment by derickr** [comment]
LGTM

**Comment by alcaeus** [comment]
Out of curiosity, the legacy driver has a magic `__get` method in `MongoCollection` which allows getting collections with a dot in the name:
```
$database->fs->files
// equivalent to
$database->selectCollection('fs.files')
```

Was this omitted by accident or deliberately?

**Comment by jmikola** [comment]
@alcaeus: Good catch! This was deliberate, as we always found the `->` chaining on MongoCollection a bit weird. It is a bit more natural in the shell, since `.` is the property accessor; however, it's more explicit if users simply do `$database->{'system.profile'}`. I'll add a note about this in the doc block, though.

**Pull request merged**
