### PR TITLE
[WIP] PHPLIB-114: Implement GridFS specification

### PR DESCRIPTION
**Pull request by jmikola**
https://jira.mongodb.org/browse/PHPLIB-114

### CODE REVIEW

**Comment by prolic** [comment]
When will this be ready?

**Comment by prolic** [comment]
If you need some help, I could spend some hours perhaps.

**Comment by jmikola** [comment]
@prolic: This is slated for 1.1. There are handful of tickets I still need to implemented for 1.0, and then I'll be revisiting this.

**Comment by jmikola** [comment]
This is being superseded by #57.

**Pull request closed without merging**
