### PR TITLE
DOCSP-10188: fix yaml file preventing docs build

### PR DESCRIPTION
**Pull request by ccho-mongodb**
This yaml file entry needs to include the interface, operation, and optional keys for the documentation to build. Please review when you get the chance so that I can publish the docs, thanks!

### CODE REVIEW

**Comment by jmikola** [comment]
Manually merged to v1.7 in https://github.com/mongodb/mongo-php-library/commit/8ff57584f582594473287dc77e1d84b30039b2e4. Thanks!

**Comment by jmikola** [comment]
@ccho-mongodb: The commit has also been merged up to master so it should fix the build for the "upcoming" branch in https://github.com/mongodb/docs-php-library/commit/4daeded3322ec857114154b5e82bad10e6bdd955. Based on that, I assume nothing is building v1.7 directly, but perhaps it makes sense to briefly point "upcoming" to v1.7 and leave master dangling. I don't feel strongly either way, as v1.7 will become "current" in just a few weeks.

**Comment by ccho-mongodb** [comment]
I see, could we also merge into master since I need to build the docs master branch (as well as every other version branch) in order to update the version selector?

**Comment by jmikola** [comment]
This has already been merged to master in https://github.com/mongodb/mongo-php-library/commit/81a57c0d1fca902ae74eb4ae24f4ca23dbb08782. That's what I meant by "has also been merged up to master" in my last comment :)

**Comment by ccho-mongodb** [comment]
Ah sorry, missed that part. There's a strange bug in the version selector such that v1.7 is not redirecting to the appropriate content which I am currently chasing with the Docs Platform team.

**Pull request closed without merging**
