### PR TITLE
[WAITING] PHPLIB-290: Remove restrictions on majority read concern for mapReduce

### PR DESCRIPTION
**Pull request by alcaeus**
https://jira.mongodb.org/browse/PHPLIB-290

### CODE REVIEW

**Comment by kvwalker** [comment]
It looks like PHPLIB-290 refers to `aggregate` and `mapReduce`, but the [linked SPEC ticket](https://jira.mongodb.org/browse/SPEC-1153) and its [final change](https://github.com/mongodb/specifications/pull/475) only refer to `aggregate`. I think this PR should only include changes for `aggregate` since the `mapReduce` `readConcern` changes depend on SEVER-38117.

**Comment by jmikola** [comment]
Good catch, @kvwalker. I updated [PHPLIB-290](https://jira.mongodb.org/browse/PHPLIB-290) and cross-referenced the new server ticket pertaining to `mapReduce()`.

**Comment by alcaeus** [comment]
Thanks @kvwalker, I wasn't aware that `mapReduce()` was split off. Given that we've already taken care of `aggregate()` in #643, I've put this PR on hold until [SERVER-38117](https://jira.mongodb.org/browse/SERVER-38117) is fixed.

**Comment by alcaeus** [comment]
Closing despite previous comment as it may be a while until the restriction on `mapReduce` is lifted.

**Pull request closed without merging**
