### PR TITLE
Add WriteConcern getter

### PR DESCRIPTION
**Pull request by JoffreyPoreeCoding**
Hi,

I made a MongoDB Object Document Mapper for PHP (You can see it [here](https://github.com/JoffreyPoreeCoding/MongoDB-ODM)) and I need to know WriteConcern of collection to check if insert/update/delete result have to be acknowledged.

I add a simple WriteConcern getter in Collection class of your library.

Hope that it will be OK.

### CODE REVIEW

**Comment by JoffreyPoreeCoding** [comment]
Hi,

Please answer me for this pull request, it's just a simple getter.

**Comment by jmikola** [comment]
It looks like I missed this PR when it was first opened. Sorry about that.

We currently have [PHPLIB-271](https://jira.mongodb.org/browse/PHPLIB-271) as a tracking ticket to add getters for _all_ options on the core classes. @petr-buchin opened https://github.com/mongodb/mongo-php-library/pull/385/files to address this, but I'm waiting to resolve [PHPLIB-261](https://jira.mongodb.org/browse/PHPLIB-261) first, which is going to allow some options to have `null` values (e.g. a default WriteConcern or ReadConcern). I expect both of those tickets to be incorporated into the upcoming 1.2.0 release.

Work was previously blocking on [PHPC-834](https://jira.mongodb.org/browse/PHPC-834), which has since been merged and will be included in the extension's upcoming 1.3.0 release.

**Comment by JoffreyPoreeCoding** [comment]
No problem, thank you for this answer.

**Comment by jmikola** [comment]
https://github.com/mongodb/mongo-php-library/pull/401 has been merged, so this can be closed. The new methods should be available in the upcoming 1.2.0 release, unless you'd like to pull 1.2.0-dev.

**Pull request closed without merging**
