### PR TITLE
PHPLIB-945: Update ChangeStreamEvent type definition to include clusterTime

### PR DESCRIPTION
**Pull request by levon80999**
https://jira.mongodb.org/browse/PHPLIB-945

Sync with mongodb/specifications@1a3b359ad3976f62d4c96f9ba75a533799c2b213

### CODE REVIEW

**Comment by jmikola** [comment]
Please add the sync commit (https://github.com/mongodb/specifications/commit/d9a0e7b2346c4d1b88fafa7419ff54ea6009ffc8) to your commit message.

**Comment by jmikola** [comment]
Note: recent discussion in [DRIVERS-2025](https://jira.mongodb.org/browse/DRIVERS-2025) indicates that there will be a follow-up ticket to update this spec test. I suggest holding off on merging so that we can re-use PHPLIB-945 and this PR for the second ticket that will soon be created.

**Comment by jmikola** [comment]
Per my [comment in PHPLIB-945](https://jira.mongodb.org/browse/PHPLIB-945?focusedCommentId=4827761&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-4827761), please sync with https://github.com/mongodb/specifications/commit/1a3b359ad3976f62d4c96f9ba75a533799c2b213.

**Comment by jmikola** [comment]
@levon80999: Note that my earlier feedback from https://github.com/mongodb/mongo-php-library/pull/971#issuecomment-1247334702 has not been addressed.

**Comment by levon80999** [comment]
> @levon80999: Note that my earlier feedback from [#971 (comment)](https://github.com/mongodb/mongo-php-library/pull/971#issuecomment-1247334702) has not been addressed.

**Review by alcaeus — APPROVED** [review]

**Pull request merged**
