### PR TITLE
Remove unused imports

### PR DESCRIPTION
**Pull request by piotr-cz**
Removed unused imports from code base.
Detected with [Intelephense for VSCode](https://marketplace.visualstudio.com/items?itemName=bmewburn.vscode-intelephense-client).

### CODE REVIEW

**Comment by alcaeus** [comment]
Thank you for your contribution! These imports are all taken care of in #668, where we add comprehensive coding standards checks via `phpcs`. I'll look through your changes again once I've merged the pull request, but I suspect that all optimisations you've done here are taken care of by that PR already.

**Comment by piotr-cz** [comment]
True, I've missed that #688. 
Probably unused imports will be taken care of there. Once that PR is merged to master, I'll check again.

**Comment by alcaeus** [comment]
#668 has been merged, so if you want to check if there's anything else, but I'd be surprised if `phpcs` missed anything 👍

**Comment by piotr-cz** [comment]
Good job, there is nothing to complain now 👍

**Pull request closed without merging**
