### PR TITLE
PHPLIB-953 Make internal classes and Operation classes final

### PR DESCRIPTION
**Pull request by GromNaN**
Fix PHPLIB-953

### CODE REVIEW

**Comment by alcaeus** [comment]
This only includes a part of the classes in the `Operation` namespace. @jmikola should we make all of those classes internal and make those final that we don't extend for our own purposes?

**Comment by GromNaN** [comment]
`@internal` I'm not sure because the operation classes can be used with `explain`. `@final` for sure, they are all composable.

**Comment by jmikola** [comment]
I suppose all Operation classes can be `@final` if you want to go that route. Those that implement Explainable should not be considered internal, as @GromNaN stated.

**Review by jmikola — APPROVED** [review]
I'll defer to you if this warrants some communication in `UPGRADE-2.0.md`.

**Review by jmikola — APPROVED** [review]

**Pull request merged**
